# Generated by Django 5.1.7 on 2025-03-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=100)),
                ('feature_value', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'car_features',
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.ImageField(upload_to='car_images/')),
                ('is_main', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'car_images',
            },
        ),
        migrations.CreateModel(
            name='CarListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('mileage', models.PositiveIntegerField()),
                ('power', models.PositiveIntegerField()),
                ('engine_capacity', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=30)),
                ('condition_state', models.CharField(choices=[('nou', 'Nou'), ('ocazie', 'Ocazie'), ('avariat', 'Avariat')], max_length=10)),
                ('year_of_manufacture', models.PositiveSmallIntegerField()),
                ('fuel_type', models.CharField(choices=[('benzina', 'Benzină'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hibrid', 'Hibrid'), ('GPL', 'GPL'), ('altele', 'Altele')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('emission_standard', models.CharField(max_length=20)),
                ('transmission', models.CharField(choices=[('manuala', 'Manuală'), ('automata', 'Automată'), ('semi-automata', 'Semi-automată')], max_length=15)),
                ('drive_type', models.CharField(choices=[('fata', 'Față'), ('spate', 'Spate'), ('4x4', '4x4')], max_length=5)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'car_listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'favorites',
            },
        ),
    ]
