# Generated by Django 5.1.7 on 2025-03-16 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('vizualizare', 'Vizualizare'), ('favorit', 'Favorit'), ('contact', 'Contact')], max_length=15)),
                ('interaction_count', models.PositiveIntegerField(default=1)),
                ('last_interaction', models.DateTimeField(auto_now=True)),
                ('car_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='listings.carlisting')),
            ],
            options={
                'db_table': 'user_interactions',
            },
        ),
    ]
